#spring.application.name=nft-marketplace-be

server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/nft-marketplace"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 220599
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"